# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nylas < Formula
  desc "CLI for Nylas API - manage email, calendar, and contacts"
  homepage "https://github.com/mqasimca/nylas"
  version "0.3.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mqasimca/nylas/releases/download/v0.3.6/nylas_0.3.6_darwin_amd64.tar.gz"
      sha256 "7769b677d808d368d20613d18c71344c65f4e862196f891f40a9f5dc40f92c46"

      def install
        bin.install "nylas"

        # Install shell completions
        generate_completions_from_executable(bin/"nylas", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mqasimca/nylas/releases/download/v0.3.6/nylas_0.3.6_darwin_arm64.tar.gz"
      sha256 "ac2edbb83fb188d6add75b300acd1748f2888cc459ecb1aff7be4c26df48975c"

      def install
        bin.install "nylas"

        # Install shell completions
        generate_completions_from_executable(bin/"nylas", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mqasimca/nylas/releases/download/v0.3.6/nylas_0.3.6_linux_amd64.tar.gz"
      sha256 "52d709e309f30536a58922fe655a3026e1ce6c5a8ea1a68eb7ea2e65621fb277"
      def install
        bin.install "nylas"

        # Install shell completions
        generate_completions_from_executable(bin/"nylas", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mqasimca/nylas/releases/download/v0.3.6/nylas_0.3.6_linux_arm64.tar.gz"
      sha256 "d0247659855319165549b8d5492c7de3080304ab7968ceb6af9bb2e4f7e3764c"
      def install
        bin.install "nylas"

        # Install shell completions
        generate_completions_from_executable(bin/"nylas", "completion")
      end
    end
  end

  test do
    system "#{bin}/nylas", "--version"
  end
end
