# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nylas < Formula
  desc "CLI for Nylas API - manage email, calendar, and contacts"
  homepage "https://github.com/mqasimca/nylas"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mqasimca/nylas/releases/download/v0.3.2/nylas_0.3.2_darwin_amd64.tar.gz"
      sha256 "da4132b6e200869ce40980ab805d7e20b34b3a25eee59b4e7dc13fa06999ed5a"

      def install
        bin.install "nylas"

        # Install shell completions
        generate_completions_from_executable(bin/"nylas", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mqasimca/nylas/releases/download/v0.3.2/nylas_0.3.2_darwin_arm64.tar.gz"
      sha256 "2210f167c5b8465c4d9dac28961c3960d364c61a44d6ad92727eafdc70ad24db"

      def install
        bin.install "nylas"

        # Install shell completions
        generate_completions_from_executable(bin/"nylas", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mqasimca/nylas/releases/download/v0.3.2/nylas_0.3.2_linux_amd64.tar.gz"
      sha256 "21f2b3a09778429389aaf869b9aacb0f1c89eee9645e1bb268ce4ba23538bd96"
      def install
        bin.install "nylas"

        # Install shell completions
        generate_completions_from_executable(bin/"nylas", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mqasimca/nylas/releases/download/v0.3.2/nylas_0.3.2_linux_arm64.tar.gz"
      sha256 "6738c18164bb866f17a66539147d184bd5c496b5b888fcb3456c8bbd60c3e7de"
      def install
        bin.install "nylas"

        # Install shell completions
        generate_completions_from_executable(bin/"nylas", "completion")
      end
    end
  end

  test do
    system "#{bin}/nylas", "--version"
  end
end
