# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nylas < Formula
  desc "CLI for Nylas API - manage email, calendar, and contacts"
  homepage "https://github.com/mqasimca/nylas"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mqasimca/nylas/releases/download/v0.2.0/nylas_0.2.0_darwin_amd64.tar.gz"
      sha256 "b49da2f2dfbf67f9ec7523455d53f6cf07f7756853b505d4e6f3b5b1fb09f413"

      def install
        bin.install "nylas"

        # Install shell completions
        generate_completions_from_executable(bin/"nylas", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mqasimca/nylas/releases/download/v0.2.0/nylas_0.2.0_darwin_arm64.tar.gz"
      sha256 "59f3cbd7ea9c16205eeef8bc26013d100f0613778cf4d40e46a3c261dfcb2b73"

      def install
        bin.install "nylas"

        # Install shell completions
        generate_completions_from_executable(bin/"nylas", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mqasimca/nylas/releases/download/v0.2.0/nylas_0.2.0_linux_amd64.tar.gz"
      sha256 "09609cf6d64d12b18f661b4df0d2b38ecd093278b25798af1ed3b640de266b87"
      def install
        bin.install "nylas"

        # Install shell completions
        generate_completions_from_executable(bin/"nylas", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mqasimca/nylas/releases/download/v0.2.0/nylas_0.2.0_linux_arm64.tar.gz"
      sha256 "77af918f37dc35cc05f89fb62a6849c39b484ae82932c51b4193a18b0c3ff8fc"
      def install
        bin.install "nylas"

        # Install shell completions
        generate_completions_from_executable(bin/"nylas", "completion")
      end
    end
  end

  test do
    system "#{bin}/nylas", "--version"
  end
end
